FROM golang:1.13

# install fresh (golang rebuilder on file change) and install gotest
RUN go get -u github.com/sc7639/fresh \
    github.com/rakyll/gotest \
    github.com/pressly/goose/cmd/goose \
    github.com/golang/protobuf/proto \
    google.golang.org/grpc \
    github.com/onsi/gomega

# Create app dir
RUN mkdir -p /app/ /app/tmp

ENV Environment development

VOLUME /app
WORKDIR /app
EXPOSE 8080

CMD ["fresh", "-c", "./config/fresh.conf"]
